vich_uploader:
    db_driver: orm

    mappings:
        identity_proof:
            uri_prefix: /images/identityProof
            upload_destination: '%kernel.project_dir%/public/images/identityProof'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        RCS:
            uri_prefix: /images/extrait_rcs
            upload_destination: '%kernel.project_dir%/public/images/extrait_rcs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        rib:
            uri_prefix: /images/rib
            upload_destination: '%kernel.project_dir%/public/images/rib'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        legalStatus:
            uri_prefix: /images/legalStatus
            upload_destination: '%kernel.project_dir%/public/images/legalStatus'
        liasseFiscale:
            uri_prefix: /images/liasseFiscale
            upload_destination: '%kernel.project_dir%/public/images/liasseFiscale'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
