vich_uploader:
    db_driver: orm

    mappings:
        identiy_proof:
            uri_prefix: /images/identityProof
            upload_destination: '%kernel.project_dir%/public/images/identityProof'
            
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
